Jakec/add html redis push
DistributedDesigns/worker pull request #6
Opened 2017-02-20 08:27 UTC by JakeCooper

Simply post to the port using the json structure

```
{"command": "ADD,jsmith,200.00"}
```

and "ADD,jsmith,200.00" will be added to that workers redis queue.

TODO Before Merge:

Figure out why the following is happening
```
00:22:24.514 ▶    ERROR 001  [x] Aborted transaction: Unrecognized command
jsmith: [ADD jsmith 200.00] txWorker.go:39
ADD,jsmith,200.00
```

Programatically bind to a free port. We have ports 44430-39.

2017-02-20 08:30 UTC, trstephen commented
@JakeCooper You're missing a transaction number in the payload. [here](https://github.com/DistributedDesigns/worker/blob/41e13a4e3463a6a9e9702290a1b41d8455ad4daa/commands.go#L29)

2017-02-20 08:31 UTC, JakeCooper commented
Ahh that will do it.

2017-02-20 08:33 UTC, JakeCooper commented
Guess that's what I get for skipping my 'Validate Command' comment. Woopsie.

2017-02-20 09:10 UTC, trstephen requested changes
Top points:
1. Need to pull config from `env.yaml` instead of baked in
1. The redis connection should have `defer conn.Close()` called. I'm not familiar with Go's http stuff so I don't know if it will stay alive within the scope of `handler` (i.e. if `handler` is invoked every time a message comes in to `/` then you'd have to get a new redis connection every time... which is bad.

 I'm really anxious to see if we can send the response after async transaction execution. Seems like the scope of this is just to get TX in to redis, though. Obviously, it gets us closer to where we want to be, though. Do you think adding an async completion message can be brought into the scope of this work or will it be considerably more effort?

2017-02-20 09:10 UTC, trstephen commented on .gitignore
> +modules.xml
Seems like this is editor config and should be in your global `.gitignore`

```sh
$ git config --global core.excludesfile ~/.gitignore_global
```

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	port := fmt.Sprintf(":%d", 44431+*workerNum)
Pull this from the config file.  `config.Redis.Port`

You'll probably have to add some entries into the config file for `nginx` stuff.

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	conn.Do("RPUSH", fmt.Sprintf("worker:%d:pendingtx", *workerNum), cmd.Command)
Check errors.

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	conn.Do("RPUSH", fmt.Sprintf("worker:%d:pendingtx", *workerNum), cmd.Command)
The list name is shared [here](https://github.com/DistributedDesigns/worker/blob/21927a2da910a5867b397c20692fce403570980d/fetchNewTx.go#L9) which is an indication that `'pendingtx'` should be a constant. Also, you can use `redisBaseKey` here.

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	fmt.Fprintf(w, responseText, r.URL.Path[1:])
Does this need to print every time? Use `consoleLog` for debugging statements.

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	fmt.Printf("Started watching on port %s\n", port)
`consoleLog`

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	var cmd commandStruct
IMO it's cleaner to use an anonymous struct for single-purpose deserialization.

```go
data := struct{ Command string }{ "" }
err := decoder.Decode(&data)
```

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	if err != nil {
use `failOnError(err)`

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	fmt.Println(cmd.Command)
Debugging?

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +	responseText := fmt.Sprintf("Successfully performed %s\n", cmd.Command)
Is this temporary? We'll need to send this message after command execution.

2017-02-20 09:10 UTC, trstephen commented on httpWatcher.go
> +func httpWatcher() {
Nit: `incomingTxWatcher`?

2017-02-27 22:18 UTC, JakeCooper commented on httpWatcher.go
> +	fmt.Fprintf(w, responseText, r.URL.Path[1:])
This isn't a print, it's a response.

2017-02-27 22:24 UTC, JakeCooper commented on httpWatcher.go
> +	fmt.Printf("Started watching on port %s\n", port)
I can add this, but I also feel like it's important to give some sort of console acknowledgement, at least for now.

2017-02-27 22:25 UTC, JakeCooper commented on httpWatcher.go
> +	responseText := fmt.Sprintf("Successfully performed %s\n", cmd.Command)
Yea, it's just a filler response ATM.

2017-02-27 22:35 UTC, JakeCooper commented
Async responses are going to have to be under another PR. For now, this will allows us to do the actual distributed work, which is great. We'll have to do responses over encrypted sockets or something like that.

Better to get these PRs merged than leaving them open to pile up and cause conflicts.

2017-02-27 23:13 UTC, JakeCooper commented
@trstephen The `redisBaseKey` should probably not include the seperator `:`.

2017-02-27 23:30 UTC, trstephen commented
LGTM. We can investigate the black magic of `http.ListenAndServer` once we actually do a deploy because I can't think of a case when it's _not_ `localhost`.

![giphy](https://cloud.githubusercontent.com/assets/6734837/23384895/aaf36100-fd01-11e6-8e37-302dec82638d.gif)

2017-02-27 23:30 UTC, trstephen approved these changes

2017-02-27 23:31 UTC, merged